language: node_js
node_js:
  - "node"
  - "8"
sudo: false
install:
  - npm install
  - npm install -g codecov

  # setup translation server
  - git clone https://github.com/zotero/translation-server
  - cd translation-server
  - npm install
  - cd ..
  - node test/util/server.js start
script:
  - npm run coverage
after_success:
  - npm run report && codecov
