name: build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Setup
      run: |
        npm install
        git clone --recursive https://github.com/zotero/translation-server
        cd translation-server
        git checkout 2.0.3
        git submodule update --init --recursive
        npm install
        node ../test/util/server.js start
        cd ..

    - name: Tests
      run: npm run coverage

    - name: After
      run: npm run report

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
